import type { Metadata } from "next";
import { Red_Hat_Text } from "next/font/google";

import "./globals.css";
const red_hat_font = Red_Hat_Text({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Frontend Mentor | Product list with cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${red_hat_font.className}`}>{children}</body>
    </html>
  );
}
